Vagrant.configure("2") do |config|
  # Definición de la primera máquina virtual
  config.vm.define "web_server" do |web|
    web.vm.box = "ubuntu/bionic64"  # Imagen base de Ubuntu Bionic
    web.vm.network "private_network", ip: "192.168.50.10"  # Red privada con IP fija
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  # Asignar 512 MB de RAM
      vb.cpus = 2        # Asignar 2 CPU
    end
  end

  # Definición de la segunda máquina virtual
  config.vm.define "db_server" do |db|
    db.vm.box = "ubuntu/bionic64"  # Imagen base de Ubuntu Bionic
    db.vm.network "private_network", ip: "192.168.50.11"  # Red privada con IP fija
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  # Asignar 512 MB de RAM
      vb.cpus = 2        # Asignar 2 CPU
    end
  end

  # Definición de la tercera máquina virtual
  config.vm.define "cache_server" do |cache|
    cache.vm.box = "ubuntu/bionic64"  # Imagen base de Ubuntu Bionic
    cache.vm.network "private_network", ip: "192.168.50.12"  # Red privada con IP fija
    cache.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  # Asignar 512 MB de RAM
      vb.cpus = 2        # Asignar 2 CPU
    end
  end
end
